StoreGraphRenderer/StoreGraphRenderer/Controllers/GraphController.cs
using StoreGraphRenderer.Data;
using StoreGraphRenderer.Enums;
using StoreGraphRenderer.Models;
using StoreGraphRenderer.Other;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;

namespace StoreGraphRenderer.Controllers
{
    public class GraphController : Controller
    {
        private int GetClusterID(string ClusterNameSelected)
        {
            //convert cluster name to id
            int clusterID = 0;

            foreach (var item in Clusters.ClusterId)
            {
                if (item.Key.ToString() == ClusterNameSelected)
                {
                    clusterID = (int)item.Value;
                }
            }
            return clusterID;
        }

        private ActionResult DisplayGraph(
            int StoreSelectedID, 
            string ClusterGroupSelected, 
            string ClusterNameSelected, 
            string StoreSelectedFloor, 
            StoredProcedures.Procedure procedure,
            string modelTitle = "",
            string modelGraphType = "column",
            string modelXAxisTitle = "",
            string modelYAxisTitle = "",
            string modelSeriesTitle = "",
            string modelSeriesAdditionalTitle = ""
            )
        {
            DataTable table = StoredProcedureHandler.Get(procedure,
                                       new Dictionary<string, string>()
                                       {
                                           { "@StoreID", StoreSelectedID.ToString() },
                                           { "@ClusterID", GetClusterID(ClusterNameSelected).ToString() },
                                           { "@FloorName", StoreSelectedFloor }
                                       });

            List<string> xData = new List<string>();
            List<string> yData = new List<string>();

            List<string> xDataAdditional = new List<string>();
            List<string> yDataAdditional = new List<string>();

            foreach (DataRow item in table.Rows)
            {
                if (item.ItemArray.Length >= 1)
                    xData.Add(item.ItemArray[0].ToString());
                if (item.ItemArray.Length >= 2)
                    yData.Add(item.ItemArray[1].ToString());
                if (item.ItemArray.Length >= 3)
                    xDataAdditional.Add(item.ItemArray[2].ToString());
                if (item.ItemArray.Length >= 4)
                    yDataAdditional.Add(item.ItemArray[3].ToString());
            }

            GraphModel model = new GraphModel();
            model.YAxisData = xData.ToArray();
            model.XAxisData = yData.ToArray();

            model.YAxisDataAdditional = xDataAdditional.ToArray();

            model.XAxisTitle = modelXAxisTitle;
            model.YAxisTitle = modelYAxisTitle;
            model.Title = modelTitle;
            model.GraphType = modelGraphType;
            model.GraphTemplate = GraphTemplate.graphTemplateInterval1000WithX50;
            model.SeriesTitleInitial = modelSeriesTitle;
            model.SeriesTitleAdditional = modelSeriesAdditionalTitle;
            var chart = GraphRenderer.RenderGraph(model);

            string imageData = ImageToBase64.Get(chart);
            if (imageData.Length > 0)
            {
                ViewBag.ImageUrl = imageData;
            }

            return View("~/Views/Graph/RenderGraph.cshtml");
        }

        // GET: Graph Total Sales - line 
        public ActionResult GetTotalSales(int StoreSelectedID, string ClusterGroupSelected, string ClusterNameSelected, string StoreSelectedFloor)
        {
            return DisplayGraph(
                StoreSelectedID, 
                ClusterGroupSelected, 
                ClusterNameSelected, 
                StoreSelectedFloor, 
                StoredProcedures.Procedure.sp_GetTotalSales,
                modelTitle: "Total Sales/Week counter",
                modelGraphType:"line",
                modelXAxisTitle:"Week counter",
                modelYAxisTitle:"Total Sales",
                modelSeriesTitle:"Weeks 13",
                modelSeriesAdditionalTitle:"Weeks 52"
                );
        }

        // GET: Graph Total Volume - line
        public ActionResult GetTotalVolume(int StoreSelectedID, string ClusterGroupSelected, string ClusterNameSelected, string StoreSelectedFloor)
        {
            return DisplayGraph(
                StoreSelectedID,
                ClusterGroupSelected,
                ClusterNameSelected,
                StoreSelectedFloor,
                StoredProcedures.Procedure.sp_GetTotalVolume,
                modelTitle: "Total Volunme/Week counter",
                modelGraphType: "line",
                modelXAxisTitle: "Week counter",
                modelYAxisTitle: "Total Volume",
                modelSeriesTitle: "Weeks 13",
                modelSeriesAdditionalTitle: "Weeks 52"
                );
        }

        // GET: Graph Total Volume - line
        public ActionResult GetAverageProfit(int StoreSelectedID, string ClusterGroupSelected, string ClusterNameSelected, string StoreSelectedFloor)
        {
            return DisplayGraph(
               StoreSelectedID,
               ClusterGroupSelected,
               ClusterNameSelected,
               StoreSelectedFloor,
               StoredProcedures.Procedure.sp_GetAverageProfit,
               modelTitle: "Average Profit/Week counter",
               modelGraphType: "line",
               modelXAxisTitle: "Week counter",
               modelYAxisTitle: "Average Profits",
               modelSeriesTitle: "Weeks 13",
               modelSeriesAdditionalTitle: "Weeks 52"
               );
        }

        // GET: Graph Average Profit Per Bay - column
        public ActionResult GetAverageProfitPerBay(int StoreSelectedID, string ClusterGroupSelected, string ClusterNameSelected, string StoreSelectedFloor)
        {
            return DisplayGraph(
               StoreSelectedID,
               ClusterGroupSelected,
               ClusterNameSelected,
               StoreSelectedFloor,
               StoredProcedures.Procedure.sp_GetAverageProfitPerBay,
               modelTitle: "",
               modelGraphType: "column",
               modelXAxisTitle: "",
               modelYAxisTitle: "",
               modelSeriesTitle: "Weeks 13",
               modelSeriesAdditionalTitle: "Weeks 52"
               );
        }

        // GET: Graph Total Sales Per Bay - column
        public ActionResult GetTotalSalesPerBay(int StoreSelectedID, string ClusterGroupSelected, string ClusterNameSelected, string StoreSelectedFloor)
        {
            return DisplayGraph(
               StoreSelectedID,
               ClusterGroupSelected,
               ClusterNameSelected,
               StoreSelectedFloor,
               StoredProcedures.Procedure.sp_GetTotalSalesPerBay,
               modelTitle: "",
               modelGraphType: "column",
               modelXAxisTitle: "",
               modelYAxisTitle: "",
               modelSeriesTitle: "Weeks 13",
               modelSeriesAdditionalTitle: "Weeks 52"
               );
        }

        // GET: Graph Total Volume Per Bay - column
        public ActionResult GetTotalVolumePerBay(int StoreSelectedID, string ClusterGroupSelected, string ClusterNameSelected, string StoreSelectedFloor)
        {
            return DisplayGraph(
               StoreSelectedID,
               ClusterGroupSelected,
               ClusterNameSelected,
               StoreSelectedFloor,
               StoredProcedures.Procedure.sp_GetTotalVolumePerBay,
               modelTitle: "",
               modelGraphType: "column",
               modelXAxisTitle: "",
               modelYAxisTitle: "",
               modelSeriesTitle: "Weeks 13",
               modelSeriesAdditionalTitle: "Weeks 52"
               );
        }

        // GET: Graph Bay Sales - line
        public ActionResult GetBaySales(int StoreSelectedID, string ClusterGroupSelected, string ClusterNameSelected, string StoreSelectedFloor, string SelectedBay)
        {
            DataTable table = StoredProcedureHandler.Get(StoredProcedures.Procedure.sp_BayGetSales,
                                      new Dictionary<string, string>()
                                      {
                                           { "@StoreID", StoreSelectedID.ToString() },
                                           { "@ClusterID", GetClusterID(ClusterNameSelected).ToString() },
                                           { "@FloorName", StoreSelectedFloor },
                                           { "@Bay", SelectedBay}
                                      });

            var tableEnumerable = table.AsEnumerable();

            GraphModel model = new GraphModel();
            model.XAxisData = tableEnumerable.Select(s => s.Field<string>("TotalSalesWeeks13")).ToList().ToArray();
            
            model.YAxisData = tableEnumerable.Select(s => s.Field<string>("TotalSalesWeeks13")).ToList().ToArray(); // retrieves point for weeks 13 
            model.YAxisDataAdditional = tableEnumerable.Select(s => s.Field<string>("TotalSalesWeeks52")).ToList().ToArray(); // retrieves point for weeks 52 

            model.XAxisTitle = "";
            model.YAxisTitle = "Total Sales";
            model.Title = "Total Sales Weeks 13/52";
            model.GraphType = "point";
            model.GraphTemplate = GraphTemplate.graphTemplateInterval100;
            
            model.SeriesTitleInitial = "Weeks 13";
            model.SeriesTitleAdditional = "Weeks 52";
            var chart = GraphRenderer.RenderGraph(model);

            string imageData = ImageToBase64.Get(chart);
            if (imageData.Length > 0)
            {
                ViewBag.ImageUrl = imageData;
            }

            return View("~/Views/Graph/RenderGraph.cshtml");
        }
   
        // GET: Graph Bay Volume - line

StoreGraphRenderer/StoreGraphRenderer/Controllers/HomeController.cs
using StoreGraphRenderer.Data;
using StoreGraphRenderer.Enums;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StoreGraphRenderer.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            DataTable table = StoredProcedureHandler.Get(StoredProcedures.Procedure.sp_GetStoreIDs, new Dictionary<string, string>(){});

            ViewBag.StoreIDs = table.Select().Select(r => r.ItemArray[0].ToString()).ToList();

            return View();
        }

        public ActionResult SelectStore(string StoreSelectedID, string StoreSelectedFloor)
        {
            DataTable table = StoredProcedureHandler.Get(StoredProcedures.Procedure.sp_GetStoreFloors, 
                                                        new Dictionary<string, string>()
                                                        {
                                                            { "@StoreID", StoreSelectedID }
                                                        });
            ViewBag.StoreSelectedID = StoreSelectedID;
            ViewBag.StoreSelectedFloor = StoreSelectedFloor;
            ViewBag.StoreFloors = table.Select().Select(r => r.ItemArray[0].ToString()).ToList();

            return View();
        }

        public ActionResult SelectFloor(string StoreSelectedID, string StoreSelectedFloor, string ClusterGroupSelected)
        {
            ViewBag.StoreSelectedID = StoreSelectedID;
            ViewBag.StoreSelectedFloor = StoreSelectedFloor;
            ViewBag.ListOfClusterGroup = Enum.GetValues(typeof(Clusters.ClusterGroup))
                                         .Cast<Clusters.ClusterGroup>()
                                         .Select(enu => enu.ToString())
                                         .ToList();
            return View();
        }

        public ActionResult SelectCluster(string StoreSelectedID, string StoreSelectedFloor, string ClusterGroupSelected)
        {
            List<string> clusterGroupToNameList = new List<string>();

            foreach (var item in Clusters.ClusterName)
            {
                if (item.Value.ToString() == ClusterGroupSelected) {
                    clusterGroupToNameList.Add(item.Key);
                }
            }

            ViewBag.StoreSelectedID = StoreSelectedID;
            ViewBag.StoreSelectedFloor = StoreSelectedFloor;
            ViewBag.ListOfClusterNames = clusterGroupToNameList;
            return View();
        }

        public ActionResult RenderButtons(int StoreSelectedID, string StoreSelectedFloor, string ClusterGroupSelected, string ClusterNameSelected)
        {
            ViewBag.StoreSelectedID = StoreSelectedID;
            ViewBag.StoreSelectedFloor = StoreSelectedFloor;
            
            //convert cluster name to id
            int clusterID = 0;

            foreach (var item in Clusters.ClusterId)
            {
                if (item.Key.ToString() == ClusterNameSelected)
                {
                    clusterID = (int)item.Value;
                }
            }

            DataTable table = StoredProcedureHandler.Get(StoredProcedures.Procedure.sp_GetBay,
                                                       new Dictionary<string, string>()
                                                       {
                                                            { "@StoreID", StoreSelectedID.ToString() },
                                                            { "@FloorName", StoreSelectedFloor },
                                                            { "@ClusterID", clusterID.ToString() },
                                                       });
            
            ViewBag.StoreBay = table.Select().Select(r => r.ItemArray[0].ToString()).ToList();

            return View();
        }

        public ActionResult SelectBay(int StoreSelectedID, string StoreSelectedFloor, string ClusterGroupSelected, string ClusterNameSelected, string SelectedBay)
        {
            ViewBag.StoreSelectedID = StoreSelectedID;
            ViewBag.StoreSelectedFloor = StoreSelectedFloor;
            
            return View();
        }
    }
}

StoreGraphRenderer/StoreGraphRenderer/Views/Home/Index.cshtml
@model StoreGraphRenderer.Models.StoreSelection

@{
    ViewBag.Title = "Home Page";
}

<p class="title">Select the store id which you would like to retrieve data for</p>

@using (Html.BeginForm("SelectStore", "Home"))
{
    @Html.DropDownListFor(store => store.StoreSelectedID, new SelectList(ViewBag.StoreIDs));
    <input type="submit" value="Select Store" />
}

StoreGraphRenderer/StoreGraphRenderer/Views/Home/RenderButtons.cshtml
@model StoreGraphRenderer.Models.ClusterSelection

@{
    ViewBag.Title = "RenderButtons";
}

<p class="title">Render graphs for the selected store</p>

@using (Html.BeginForm("GetTotalSales", "Graph"))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(group => group.ClusterGroupSelected);
    @Html.HiddenFor(name => name.ClusterNameSelected);
    <input type="submit" value="Get total sales"/>
}

@using (Html.BeginForm("GetTotalVolume", "Graph"))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(group => group.ClusterGroupSelected);
    @Html.HiddenFor(name => name.ClusterNameSelected);
    <input type="submit" value="Get total volume" />
}

@using (Html.BeginForm("GetAverageProfit", "Graph"))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(group => group.ClusterGroupSelected);
    @Html.HiddenFor(name => name.ClusterNameSelected);
    <input type="submit" value="Get average profit" />
}

@using (Html.BeginForm("GetAverageProfitPerBay", "Graph"))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(group => group.ClusterGroupSelected);
    @Html.HiddenFor(name => name.ClusterNameSelected);
    <input type="submit" value="Get average profit per bay" />
}

@using (Html.BeginForm("GetTotalSalesPerBay", "Graph"))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(group => group.ClusterGroupSelected);
    @Html.HiddenFor(name => name.ClusterNameSelected);
    <input type="submit" value="Get total sales per bay" />
}

@using (Html.BeginForm("GetTotalVolumePerBay", "Graph"))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(group => group.ClusterGroupSelected);
    @Html.HiddenFor(name => name.ClusterNameSelected);
    <input type="submit" value="Get Total Volume per bay" />
}

<p class="title">Select store specific bay</p>

@using (Html.BeginForm("SelectBay", "Home", FormMethod.Post, new { @class="select-bay"}))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(group => group.ClusterGroupSelected);
    @Html.HiddenFor(name => name.ClusterNameSelected);


    @Html.DropDownListFor(bay => bay.SelectedBay, new SelectList(ViewBag.StoreBay), "Select Bay");
    <input type="submit" value="Select" />
}

StoreGraphRenderer/StoreGraphRenderer/Views/Home/SelectBay.cshtml
@model StoreGraphRenderer.Models.ClusterSelection

@{
    ViewBag.Title = "SelectBay";
}

@using (Html.BeginForm("GetBaySales", "Graph"))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(cGroup => cGroup.ClusterGroupSelected);
    @Html.HiddenFor(cName => cName.ClusterNameSelected);
    @Html.HiddenFor(cBay => cBay.SelectedBay);

    <input type="submit" value="Get Bay Sales"/>
}

@using (Html.BeginForm("GetBayVolume", "Graph"))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(cGroup => cGroup.ClusterGroupSelected);
    @Html.HiddenFor(cName => cName.ClusterNameSelected);
    @Html.HiddenFor(cBay => cBay.SelectedBay);

    <input type="submit" value="Get Bay Volume" />
}

@using (Html.BeginForm("GetBayAverageProfit", "Graph"))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(cGroup => cGroup.ClusterGroupSelected);
    @Html.HiddenFor(cName => cName.ClusterNameSelected);
    @Html.HiddenFor(cBay => cBay.SelectedBay);

    <input type="submit" value="Get Bay Average Profit" />
}

@{ 
    // some pie charts to come
}

@using (Html.BeginForm("GetTotalVolumeSalesPerBay", "Graph"))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(cGroup => cGroup.ClusterGroupSelected);
    @Html.HiddenFor(cName => cName.ClusterNameSelected);
    @Html.HiddenFor(cBay => cBay.SelectedBay);

    <input type="submit" value="Get total volume/sales" />
}

@using (Html.BeginForm("GetTotalSalesProfitPerBay", "Graph"))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(cGroup => cGroup.ClusterGroupSelected);
    @Html.HiddenFor(cName => cName.ClusterNameSelected);
    @Html.HiddenFor(cBay => cBay.SelectedBay);

    <input type="submit" value="Get total sales/profits" />
}

@using (Html.BeginForm("GetTotalVolumeProfitPerBay", "Graph"))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(cGroup => cGroup.ClusterGroupSelected);
    @Html.HiddenFor(cName => cName.ClusterNameSelected);
    @Html.HiddenFor(cBay => cBay.SelectedBay);

    <input type="submit" value="Get total volume/profit" />
}

@using (Html.BeginForm("GetTotalSalesVolumeProfitPerBay", "Graph"))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(cGroup => cGroup.ClusterGroupSelected);
    @Html.HiddenFor(cName => cName.ClusterNameSelected);
    @Html.HiddenFor(cBay => cBay.SelectedBay);

    <input type="submit" value="Get total sales,volume and profit" />
}

StoreGraphRenderer/StoreGraphRenderer/Views/Home/SelectCluster.cshtml
@model StoreGraphRenderer.Models.ClusterSelection

@{
    ViewBag.Title = "SelectCluster";
}

<p class="title">Select the compass location of the store</p>

@using (Html.BeginForm("RenderButtons", "Home"))
{
    <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
    <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

    @Html.HiddenFor(group => group.ClusterGroupSelected);
    @Html.DropDownListFor(name => name.ClusterNameSelected, new SelectList(ViewBag.ListOfClusterNames));
    <input type="submit" value="Select" />
}

StoreGraphRenderer/StoreGraphRenderer/Views/Home/SelectFloor.cshtml
@model StoreGraphRenderer.Models.ClusterSelection

@{
    ViewBag.Title = "SelectFloor";
}

<p class="title">Select the way the store should be searhed by</p>

@using (Html.BeginForm("SelectCluster", "Home"))
    {
        <input type="hidden" name="StoreSelectedID" value="@ViewBag.StoreSelectedID" />
        <input type="hidden" name="StoreSelectedFloor" value="@ViewBag.StoreSelectedFloor" />

        @Html.DropDownListFor(group => group.ClusterGroupSelected, new SelectList(ViewBag.ListOfClusterGroup));
        <input type="submit" value="Select" />
    }

StoreGraphRenderer/StoreGraphRenderer/Views/Home/SelectStore.cshtml
@model StoreGraphRenderer.Models.StoreSelection

@{
    ViewBag.Title = "SelectStore";
}

<p class="title">Select the floor for the store</p>

@using (Html.BeginForm("SelectFloor", "Home"))
{
    @Html.HiddenFor(id => id.StoreSelectedID);
    @Html.DropDownListFor(floor => floor.StoreSelectedFloor, new SelectList(ViewBag.StoreFloors));
    <input type="submit" value="Select" />
}